### PR TITLE
Feature/swap old new pages

### PR DESCRIPTION
**Pull request by jjm3x3**
This is the final code change necessary to swap the pages in for the new season of the Amazing Race and the league that will be built for it. In this change I am taking the advice described in #60 . So the old pages will be put in a location which won't collide with any other old leagues in the `/archive/AmazingRace_35/` dir/path so that it is simple to get back to them, but they should never need to move again.

### CODE REVIEW

**Review by CAnthonySiever — APPROVED** [review]
Everything looks good! 👍 Are we planning on keeping an archive for each season like this?

**Comment by jjm3x3** [comment]
> Everything looks good! 👍 Are we planning on keeping an archive for each season like this?

Yeah, I am thinking it's easy enough to do, plus people might want to go back and see what happened in previous leagues. WDYT?

Also keep in mind that in the near future I am thinking of doing a redesign that will expose these pages in the UI.

**Comment by CAnthonySiever** [comment]
> > Everything looks good! 👍 Are we planning on keeping an archive for each season like this?
> 
> Yeah, I am thinking it's easy enough to do, plus people might want to go back and see what happened in previous leagues. WDYT?
> 
> Also keep in mind that in the near future I am thinking of doing a redesign that will expose these pages in the UI.

Yeah it makes sense to have something like "View previous winners or scores" or something along those lines.

**Comment by internette** [comment]
Fix your goddamn url naming

**Comment by jjm3x3** [comment]
> Fix your goddamn url naming
> 
> Edit for professional sake: Please fix your url naming

I am going to need some more actionable feedback in order to address this... 😞

**Comment by internette** [comment]
> > Fix your goddamn url naming
> > Edit for professional sake: Please fix your url naming
> 
> I am going to need some more actionable feedback in order to address this... 😞

All URLs should be 100% lowercase. If you want to separate words, preferably use underscores. You *can* use dashes pr %20, but that's ill-advised.

**Comment by jjm3x3** [comment]
> > > Fix your goddamn url naming
> > > Edit for professional sake: Please fix your url naming
> > 
> > 
> > I am going to need some more actionable feedback in order to address this... 😞
> 
> All URLs should be 100% lowercase. If you want to separate words, preferably use underscores. You _can_ use dashes pr %20, but that's ill-advised.

-----

> All URLs should be 100% lowercase.

I would like some source to back this up

> If you want to separate words, preferably use underscores. You _can_ use dashes pr %20, but that's ill-advised.

Also a quick web search and [one of the top results, from google](https://developers.google.com/search/docs/crawling-indexing/url-structure) actually suggests `-` over `_`? What's that about?

**Review by internette — APPROVED** [review]

**Pull request merged**
